apiVersion: v1
kind: Service
metadata:
  name: rspark-ingest
  namespace: rspark
spec:
  type: ClusterIP
  selector:
    app: rspark-ingest
  ports:
    - name: http
      port: 8081
      targetPort: http